---
- name: Configure Kafka
  template:
    src: server.properties.j2
    dest: "{{ kafka_home }}/kafka_{{ scala_kafka_version }}/config/server.properties"
  vars:
    broker_id: "{{ hostvars[inventory_hostname]['kafka_broker_id'] }}"
