---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required dependencies
  apt:
    name:
      - openjdk-11-jdk
      - curl
      - wget
    state: present

- name: Create Kafka directory
  file:
    path: "{{ kafka_home }}"
    state: directory
    owner: root
    group: root

- name: Download and extract Kafka
  unarchive:
    src: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_kafka_version }}.tgz"
    dest: "{{ kafka_home }}"
    remote_src: yes
    creates: "{{ kafka_home }}/kafka_{{ scala_kafka_version }}"
