global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['broker1:9308', 'broker2:9308', 'broker3:9308']

  - job_name: 'kafka_jmx_exporter'
    static_configs:
      - targets: 
        - 'broker1:7071'  
        - 'broker2:7071'  
        - 'broker3:7071'  

